export const CATEGORY_ICONS: Record<string, string> = {
  Agroindustria: '🌾',
  'Comercio Exterior': '🌐',
  Logística: '📦',
  'Grandes Superficies': '🏪',
  Belleza: '💇',
  Salud: '❤️',
  Fitness: '💪',
  Alimentación: '🍎',
  Educación: '📚',
  Hotelería: '🏨',
  Mecánica: '🔧',
  Artesanía: '🎨',
  Moda: '👕',
  Fotografía: '📷',
  Bienestar: '🧖',
  Inmobiliaria: '🏠',
  Legal: '⚖️',
  Finanzas: '📈',
  Entretenimiento: '🎮',
  Restaurantes: '🍽️',
  Bar: '🍺',
  Cafetería: '☕',
  Estanco: '🏪',
  Psicología: '🧠',
  Veterinaria: '🐾',
  Tecnología: '💻',
  Limpieza: '🧹',
  Construcción: '🔨',
  Transporte: '🚚',
  Turismo: '🧭',
  Diseño: '✏️',
  Jardinería: '🌿',
  Música: '🎵',
  'Cuidado Infantil': '👶',
  Profesionales: '💼',
};

export function getCategoryIcon(name: string): string {
  return CATEGORY_ICONS[name] || '📋';
}
